### ISSUE TITLE
Minecraft crashes at loading

### ISSUE THREAD

**Issue by theavandiepen** [Up-Mods/Sparkweave#1]
I tried loading Minecraft with ONLY Sparkweave Engine and qfapi and Minecraft crashed. (Discovered while troubleshooting crashes after finding that [Minecraft was crashing after I installed the latest version of Arcanus Continuum](https://github.com/Up-Mods/Arcanus-Continuum/issues/11))

[crash-2023-10-10_14.47.39.6415-quilt_loader.txt](https://github.com/Up-Mods/Sparkweave/files/12861701/crash-2023-10-10_14.47.39.6415-quilt_loader.txt)

**Comment by UpcraftLP** [comment]
Ohno.. that mixin should have never been applied outside of dev in the first place

**Comment by theavandiepen** [comment]
Thank you so much!
